language: java
jdk: oraclejdk8
branches:
  only:
  - master
notifications:
    email: false
install: mvn clean deploy --settings travis-settings.xml -B
before_install:
  - echo $GPG_PRIVATEKEY | $GPG_EXECUTABLE --import;